version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: demo_java_springboot
      MYSQL_DATABASE: demo_java_springboot
      MYSQL_USER: khanhnt3
      MYSQL_PASSWORD: khanhnt3
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
